/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthUsingAuthRouteImport } from './routes/_auth/using-auth'
import { Route as AppUsingThemeRouteImport } from './routes/_app/using-theme'
import { Route as AppUsingStoreRouteImport } from './routes/_app/using-store'
import { Route as AppUsingDataRouteImport } from './routes/_app/using-data'
import { Route as AppStreamingRouteImport } from './routes/_app/streaming'
import { Route as AppPrefetchTargetRouteImport } from './routes/_app/prefetch-target'
import { Route as AppPrefetchRouteImport } from './routes/_app/prefetch'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppDataOnlyRouteImport } from './routes/_app/data-only'
import { Route as AppClientOnlyRouteImport } from './routes/_app/client-only'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppWildcardSplatRouteImport } from './routes/_app/wildcard.$'
import { Route as AppFormIdRouteImport } from './routes/_app/form.$id'
import { Route as AppActionsFormRouteImport } from './routes/_app/actions/form'
import { Route as AppActionsDataRouteImport } from './routes/_app/actions/data'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthUsingAuthRoute = AuthUsingAuthRouteImport.update({
  id: '/using-auth',
  path: '/using-auth',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsingThemeRoute = AppUsingThemeRouteImport.update({
  id: '/using-theme',
  path: '/using-theme',
  getParentRoute: () => AppRoute,
} as any)
const AppUsingStoreRoute = AppUsingStoreRouteImport.update({
  id: '/using-store',
  path: '/using-store',
  getParentRoute: () => AppRoute,
} as any)
const AppUsingDataRoute = AppUsingDataRouteImport.update({
  id: '/using-data',
  path: '/using-data',
  getParentRoute: () => AppRoute,
} as any)
const AppStreamingRoute = AppStreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => AppRoute,
} as any)
const AppPrefetchTargetRoute = AppPrefetchTargetRouteImport.update({
  id: '/prefetch-target',
  path: '/prefetch-target',
  getParentRoute: () => AppRoute,
} as any)
const AppPrefetchRoute = AppPrefetchRouteImport.update({
  id: '/prefetch',
  path: '/prefetch',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppDataOnlyRoute = AppDataOnlyRouteImport.update({
  id: '/data-only',
  path: '/data-only',
  getParentRoute: () => AppRoute,
} as any)
const AppClientOnlyRoute = AppClientOnlyRouteImport.update({
  id: '/client-only',
  path: '/client-only',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppWildcardSplatRoute = AppWildcardSplatRouteImport.update({
  id: '/wildcard/$',
  path: '/wildcard/$',
  getParentRoute: () => AppRoute,
} as any)
const AppFormIdRoute = AppFormIdRouteImport.update({
  id: '/form/$id',
  path: '/form/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppActionsFormRoute = AppActionsFormRouteImport.update({
  id: '/actions/form',
  path: '/actions/form',
  getParentRoute: () => AppRoute,
} as any)
const AppActionsDataRoute = AppActionsDataRouteImport.update({
  id: '/actions/data',
  path: '/actions/data',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRoute
  '/client-only': typeof AppClientOnlyRoute
  '/data-only': typeof AppDataOnlyRoute
  '/login': typeof AppLoginRoute
  '/prefetch': typeof AppPrefetchRoute
  '/prefetch-target': typeof AppPrefetchTargetRoute
  '/streaming': typeof AppStreamingRoute
  '/using-data': typeof AppUsingDataRoute
  '/using-store': typeof AppUsingStoreRoute
  '/using-theme': typeof AppUsingThemeRoute
  '/using-auth': typeof AuthUsingAuthRoute
  '/actions/data': typeof AppActionsDataRoute
  '/actions/form': typeof AppActionsFormRoute
  '/form/$id': typeof AppFormIdRoute
  '/wildcard/$': typeof AppWildcardSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRoute
  '/client-only': typeof AppClientOnlyRoute
  '/data-only': typeof AppDataOnlyRoute
  '/login': typeof AppLoginRoute
  '/prefetch': typeof AppPrefetchRoute
  '/prefetch-target': typeof AppPrefetchTargetRoute
  '/streaming': typeof AppStreamingRoute
  '/using-data': typeof AppUsingDataRoute
  '/using-store': typeof AppUsingStoreRoute
  '/using-theme': typeof AppUsingThemeRoute
  '/using-auth': typeof AuthUsingAuthRoute
  '/actions/data': typeof AppActionsDataRoute
  '/actions/form': typeof AppActionsFormRoute
  '/form/$id': typeof AppFormIdRoute
  '/wildcard/$': typeof AppWildcardSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/client-only': typeof AppClientOnlyRoute
  '/_app/data-only': typeof AppDataOnlyRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/prefetch': typeof AppPrefetchRoute
  '/_app/prefetch-target': typeof AppPrefetchTargetRoute
  '/_app/streaming': typeof AppStreamingRoute
  '/_app/using-data': typeof AppUsingDataRoute
  '/_app/using-store': typeof AppUsingStoreRoute
  '/_app/using-theme': typeof AppUsingThemeRoute
  '/_auth/using-auth': typeof AuthUsingAuthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/actions/data': typeof AppActionsDataRoute
  '/_app/actions/form': typeof AppActionsFormRoute
  '/_app/form/$id': typeof AppFormIdRoute
  '/_app/wildcard/$': typeof AppWildcardSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client-only'
    | '/data-only'
    | '/login'
    | '/prefetch'
    | '/prefetch-target'
    | '/streaming'
    | '/using-data'
    | '/using-store'
    | '/using-theme'
    | '/using-auth'
    | '/actions/data'
    | '/actions/form'
    | '/form/$id'
    | '/wildcard/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/client-only'
    | '/data-only'
    | '/login'
    | '/prefetch'
    | '/prefetch-target'
    | '/streaming'
    | '/using-data'
    | '/using-store'
    | '/using-theme'
    | '/using-auth'
    | '/actions/data'
    | '/actions/form'
    | '/form/$id'
    | '/wildcard/$'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/admin'
    | '/_app/client-only'
    | '/_app/data-only'
    | '/_app/login'
    | '/_app/prefetch'
    | '/_app/prefetch-target'
    | '/_app/streaming'
    | '/_app/using-data'
    | '/_app/using-store'
    | '/_app/using-theme'
    | '/_auth/using-auth'
    | '/_app/'
    | '/_app/actions/data'
    | '/_app/actions/form'
    | '/_app/form/$id'
    | '/_app/wildcard/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/using-auth': {
      id: '/_auth/using-auth'
      path: '/using-auth'
      fullPath: '/using-auth'
      preLoaderRoute: typeof AuthUsingAuthRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/using-theme': {
      id: '/_app/using-theme'
      path: '/using-theme'
      fullPath: '/using-theme'
      preLoaderRoute: typeof AppUsingThemeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/using-store': {
      id: '/_app/using-store'
      path: '/using-store'
      fullPath: '/using-store'
      preLoaderRoute: typeof AppUsingStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/using-data': {
      id: '/_app/using-data'
      path: '/using-data'
      fullPath: '/using-data'
      preLoaderRoute: typeof AppUsingDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/streaming': {
      id: '/_app/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof AppStreamingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prefetch-target': {
      id: '/_app/prefetch-target'
      path: '/prefetch-target'
      fullPath: '/prefetch-target'
      preLoaderRoute: typeof AppPrefetchTargetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prefetch': {
      id: '/_app/prefetch'
      path: '/prefetch'
      fullPath: '/prefetch'
      preLoaderRoute: typeof AppPrefetchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-only': {
      id: '/_app/data-only'
      path: '/data-only'
      fullPath: '/data-only'
      preLoaderRoute: typeof AppDataOnlyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client-only': {
      id: '/_app/client-only'
      path: '/client-only'
      fullPath: '/client-only'
      preLoaderRoute: typeof AppClientOnlyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wildcard/$': {
      id: '/_app/wildcard/$'
      path: '/wildcard/$'
      fullPath: '/wildcard/$'
      preLoaderRoute: typeof AppWildcardSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/form/$id': {
      id: '/_app/form/$id'
      path: '/form/$id'
      fullPath: '/form/$id'
      preLoaderRoute: typeof AppFormIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/actions/form': {
      id: '/_app/actions/form'
      path: '/actions/form'
      fullPath: '/actions/form'
      preLoaderRoute: typeof AppActionsFormRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/actions/data': {
      id: '/_app/actions/data'
      path: '/actions/data'
      fullPath: '/actions/data'
      preLoaderRoute: typeof AppActionsDataRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppClientOnlyRoute: typeof AppClientOnlyRoute
  AppDataOnlyRoute: typeof AppDataOnlyRoute
  AppLoginRoute: typeof AppLoginRoute
  AppPrefetchRoute: typeof AppPrefetchRoute
  AppPrefetchTargetRoute: typeof AppPrefetchTargetRoute
  AppStreamingRoute: typeof AppStreamingRoute
  AppUsingDataRoute: typeof AppUsingDataRoute
  AppUsingStoreRoute: typeof AppUsingStoreRoute
  AppUsingThemeRoute: typeof AppUsingThemeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppActionsDataRoute: typeof AppActionsDataRoute
  AppActionsFormRoute: typeof AppActionsFormRoute
  AppFormIdRoute: typeof AppFormIdRoute
  AppWildcardSplatRoute: typeof AppWildcardSplatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppClientOnlyRoute: AppClientOnlyRoute,
  AppDataOnlyRoute: AppDataOnlyRoute,
  AppLoginRoute: AppLoginRoute,
  AppPrefetchRoute: AppPrefetchRoute,
  AppPrefetchTargetRoute: AppPrefetchTargetRoute,
  AppStreamingRoute: AppStreamingRoute,
  AppUsingDataRoute: AppUsingDataRoute,
  AppUsingStoreRoute: AppUsingStoreRoute,
  AppUsingThemeRoute: AppUsingThemeRoute,
  AppIndexRoute: AppIndexRoute,
  AppActionsDataRoute: AppActionsDataRoute,
  AppActionsFormRoute: AppActionsFormRoute,
  AppFormIdRoute: AppFormIdRoute,
  AppWildcardSplatRoute: AppWildcardSplatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthUsingAuthRoute: typeof AuthUsingAuthRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUsingAuthRoute: AuthUsingAuthRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
